pages:
  - Home: 'index.md'
  - User Documentation:
    - Installing: 'installing.md'
    - Style Guide: 'styleguide.md'
  - Software Documentation:
    - Overview: 'software/overview.md'
    - Stack Vision: 'software/stack_vision.md'
    - Provider DVL: 'software/provider_dvl.md'
    - Provider IMU: 'software/provider_imu.md'
    - Provider Sonar: 'software/provider_sonar.md'
    - Provider Media: 'software/provider_media.md'
    - Provider CAN: 'software/provider_can.md'
  - Electrical Documentation:
    - Overview: 'electrical/overview.md'
    - Hydrophones: 'electrical/hydrophones.md'

site_name: S.O.N.I.A. Documentation
repo_url: https://github.com/sonia-auv/documentation

markdown_extensions:
  - admonition
  - smarty
  - sane_lists

theme: readthedocs
