pages:
  - Home: 'index.md'
  - User Documentation:
    - Installing: 'installing.md'
    - Style Guide: 'styleguide.md'
  - Software Documentation:
    - Vision Stack:
      - Design: 'stack_vision/design.md'
      - ROS Interface: 'stack_vision/ros_interface.md'
    - Providers:
      - DVL: 'providers/dvl.md'
      - IMU: 'providers/imu.md'
      - Sonar: 'providers/sonar.md'
      - Media: 'providers/media.md'
      - CAN Server: 'providers/can.md'

site_name: S.O.N.I.A. Documentation
repo_url: https://github.com/sonia-auv/documentation

markdown_extensions:
  - admonition
  - smarty
  - sane_lists

theme: readthedocs
