pages:
  - Home: 'index.md'
  - User Documentation:
    - Installing: 'installing.md'
    - Style Guide: 'styleguide.md'

site_name: S.O.N.I.A. Documentation
repo_url: https://github.com/sonia-auv/documentation

markdown_extensions:
  - admonition
  - smarty
  - sane_lists

theme: readthedocs
